vaadin/vaadin-combo-box-flow

src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxPage.java
src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxPageIT.java

The bug was fixed in https://github.com/vaadin/vaadin-combo-box-flow/issues/48 , this PR only adds tests for the specific issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/54)

Add tests to validate the isFromClient flag on ValueChangeEvents

---

pom.xml

platform uses text-field-2.0.0-beta2 but combo-box-flow seems to force it to beta1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/55)

Use combo-box-4.0.0-beta2 and text-field-2.0.0-beta2

---

src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java

The input consumer must be serializable because it is captured
by a SerializableConsumer
Fixes #61
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/62)

Make ComboBox.runBeforeClientResponse accept SerializableConsumer

---

src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/69)

Custom values should be implicitly allowed if a value listener is assigned

---

src/test/java/com/vaadin/flow/component/combobox/test/RefreshDataProviderIT.java

After web component update, the combo-box overlay is not attached if
there are no items to display. This caused one test to fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/113)

Fix IT after updated webjar

---

src/main/java/com/vaadin/flow/component/combobox/ComboBox.java

Fixes #118 .
When using binder with combobox, setting value, clearing it and
resetting value combobox ends up empty, for value is refreshed as
empty string (set in value clear) after the correct value (set bean
in binder) was first set.
Refresh occurs in client-side property flushing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/119)

Remove value-property in component value clear.

---

src/main/java/com/vaadin/flow/component/combobox/ComboBox.java

* Fixes issue https://github.com/vaadin/vaadin-combo-box-flow/issues/118 .
When using binder with combobox, setting value, clearing it and
resetting value combobox ends up empty, for value is refreshed as
empty string (set in value clear) after the correct value (set bean
in binder) was first set.
Refresh occurs in client-side property flushing.
* Comments fixed.
Creating a regression test for this fix is complicated. Only scenario
that have shown this issue, is within bakery-application user editing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/120)

Remove value-property in component value clear (#119)

---

src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java
src/test/java/com/vaadin/flow/component/combobox/bean/TestItem.java
src/test/java/com/vaadin/flow/component/combobox/test/DataProviderIT.java
src/test/java/com/vaadin/flow/component/combobox/test/DataProviderPage.java

* Using DataProvider::getId in setValue to find the item
Fixes #111
* Adding two unit tests for exceptional cases of setValue
and renaming IT method names based on Flow naming convention.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/121)

Using DataProvider::getId in setValue to find the item (#117)

---

src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java

It used to generate a json-object even for null with just an empty
label. This caused the "clear value"-button with "x" to be shown even
when the value was null.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/141)

Clear selectedItem on setValue(null)

---

src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
src/test/java/com/vaadin/flow/component/combobox/test/FilteringIT.java
src/test/java/com/vaadin/flow/component/combobox/test/FilteringPage.java

When using the overload that takes just a DataProvider, use server-side
filtering so that a filter defined in the DataProvider is used. There's
still an overload with ListDataProvider which allows client-side
filtering.
Fixes #140
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/143)

Use filtering configured in DataProvider

---

src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
src/test/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java
src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxIT.java

Added information about the client-side filtering and page size to the
first place where users tried to find it: in setItems().
Added demo about using ItemFilter also to ComponentRenderer demo,
because it is hard to create a lambda with two parameters and it's best
to see an example. This increases the chance of finding such example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/144)

Improve javadocs and demo based on DX tests

---

src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java

When no items match the filter, the dataProvider callback was left
hanging and the spinner was never removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/153)

Fix loading indicator when server returns zero items

---

src/main/java/com/vaadin/flow/component/combobox/ComboBox.java

This should fix input element value not being empty when setting value to null. This is because the JS selectedItemChanged method does not update value unless customInput is disabled due to selectedItem being set to null each time the input no longer matches a dropdown option.
This should fix #180 but does not address another issue that caused numbers to be displayed. I will open an issue for this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/186)

Fix: value is not updated when null in ComboBox

---

src/main/java/com/vaadin/flow/component/combobox/ComboBox.java

Initializes the $connector property on ComboBox's element if this was not done prior to changing DataCommunicator by calling the comboBoxConnector.initLazy() function.
Should fix #169
The first commit is in pull #186 and fixes #180 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/188)

 Initialize $connector if values were not set in ComboBox element prior to page load.

---

pom.xml
src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
src/test/java/com/vaadin/flow/component/combobox/test/AbstractComboBoxIT.java
src/test/java/com/vaadin/flow/component/combobox/test/AutoFocusFilterIT.java
src/test/java/com/vaadin/flow/component/combobox/test/AutoFocusFilterPage.java
src/test/java/com/vaadin/flow/component/combobox/test/ClientSideFilterIT.java
src/test/java/com/vaadin/flow/component/combobox/test/ClientSideFilterPage.java
src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxPageIT.java
src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingPage.java
src/test/java/com/vaadin/flow/component/combobox/test/NullValueChangeIT.java
src/test/java/com/vaadin/flow/component/combobox/test/NullValueChangePage.java
src/test/java/com/vaadin/flow/component/combobox/test/RequiredComboboxIT.java
src/test/java/com/vaadin/flow/component/combobox/test/RequiredComboboxPage.java
src/test/java/com/vaadin/flow/component/combobox/test/SetItemsLaterIT.java
src/test/java/com/vaadin/flow/component/combobox/test/SetItemsLaterPage.java
src/test/java/com/vaadin/flow/component/combobox/test/template/ComboBoxInATemplate.java
src/test/java/com/vaadin/flow/component/combobox/test/template/ComboBoxInATemplate2.java
src/test/java/com/vaadin/flow/component/combobox/test/template/ComboBoxInTemplateIT.java
src/test/java/com/vaadin/flow/component/combobox/test/template/ComboBoxInTemplatePage.java
src/test/java/com/vaadin/flow/component/combobox/test/template/WrapperTemplate.java
src/test/webapp/frontend/src/combo-box-in-a-template2.html
src/test/webapp/frontend/src/wrapper-template.html

Cherry-picks:
- removed obsolete jetty version (#165) 
- Set value-property with js as a workaround (#174) 
- Fix: value is not updated when null in ComboBox (#186) 
- Add IT test for #186. (#189) 
-  Initialize $connector if values were not set in ComboBox element prior to page load. (#188)
- IT test for #188 (#190) 
- Set filter on autofocus combobox (#191) 
- Client side filter fix. (#192)
- Disable client side validation on setRequiredIndicatorVisible (#202)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/203)

2.0.3 cherry picks

---

.gitignore
vaadin-combo-box-flow-integration-tests/build-tools/package.json
vaadin-combo-box-flow-integration-tests/pom.xml
vaadin-combo-box-flow-integration-tests/src/main/webapp/frontend/bower.json

This allows installing any GitHub branch of the web component, to test how
the changes in the web component affect the Flow counterpart, by
defining the property -DuseBower. The branch can be specified in the
added bower.json (default is master).
Running 'mvn clean' will remove the bower components.
The configuration is based on vaadin-crud-flow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/204)

Add maven profile to use bower in integration tests

---

vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/bean/SimpleBean.java
vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/RefreshDataProviderPage.java
vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/RefreshDataProviderIT.java
vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java

Fix #184
The client-side part was already implemented in the connector, just never triggered by the data refresh event.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/209)

Update only one item on DataProvider::refreshItem

---

vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/LazyLoadingPage.java
vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java

Test for a bug fixed in the web component:
https://github.com/vaadin/vaadin-combo-box/pull/772
Close #178
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/206)

Add IT for resolving loading state when 0 items returned

---

vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/LazyLoadingPage.java
vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java
vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java

Fix #216
The problem was that the server-side value-property did not match the
key of the set item. When the value-prop was later set with js as a
workaround for a Flow bug (see the lines below the added line in
ComboBox.java), that value did not match the selectedItem, which caused
the value to become null.
(Note: server-side key is used as the client-side value-property)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/229)

Update value-property on setValue

---

vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java

Now it is not called when using a lazy data provider, because
- the size is used to check if client-side filtering can be used
- lazy data providers always handle filtering in server-side anyway
Fix #222
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/230)

Avoid calling DataProvider::size when it's not needed

---

vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/AbstractComboBoxIT.java
vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java
vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java

Otherwise, DataProvider will get a new instance of the filter object
-> DataCommunicator thinks filter changed
-> destroys all data
-> rendered components are destroyed
-> client still thinks that everything is fine
-> flow-component-renderer doesn't find destroyed component instances
-> components not rendered
Fix #227
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/231)

Don't apply new filter to DP if filter not changed

---

vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/AbstractComboBoxIT.java
vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java
vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js

because it breaks flow-component-renderer.
Fix #232
Any other solutions would be a lot more complex workarounds. Since iron-list does not provide any kind of API for reacting to focus item changes, we should somehow recognize in the `flow-component-renderer` when its child is detached, or when the first item is scrolled back into the view, and call `_attachRenderedComponentIfAble()`.
I think this workaround is the best solution, as it's a one-liner and does not require creating a custom `flow-component-renderer` for combo box.
A note about the test: the existing test case covers this when we exclude the focus item from the found item elements (it's "hidden" by translating it out of the viewport).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

Disable iron-list's focus management

---

vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java

The assertRendered helper waits for some content to be actually visible
in the items.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/251)

Improve flaky test

---

vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/CustomValuePage.java
vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/CustomValueIT.java
vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js

If preventDefault is not called, the web component will automatically
set the custom value as the value-property of combo box. This breaks the
Flow component, which uses the key of the currently selected Java bean
as the value-property.
Docs are improved to explain that it's the developer's responsibility to
handle the custom-value-set events, as we can't automatically convert
the custom string to an arbitrary bean type.
Integration tests are added, as previously none existed for this
feature.
Fix #236
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/255)

Prevent default on custom-value-set, improve javadocs

---

vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/ComboBoxPage.java
vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxPageIT.java
vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java

Otherwise the selectedItem label is not updated, when
setItemLabelGenerator is used after setValue.
fix #195
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/260)

Regenerate selectedItem after setItemLabelGenerator

---

vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java

Concerns https://github.com/vaadin/flow/issues/6177
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/284)

JsModule path relative to frontend should start with './'

---

vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/DetachReattachPage.java
vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/DetachReattachIT.java
vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js

This should be a one-time update when data is requested from the server.
Keeping the value at server-side with setProperty causes it to be sent
to client after value changes, when the _selectedKey is outdated.
Fix #305
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/306)

fix: send _selectedKey to client only once

---

vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java
vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js

Fixes #304 
This commit removes that hack with dynamically updating the Web Component's `value` / `selectedItem.key` after item remap which turned out to be problematic. The new approach overrides the `_isItemSelected` logic to also consider item remapping when highlighting selection.
By remapping I mean what happens when you scroll away from the currently selected item so that the range which included the selected item gets discarded and later returning to that range so that the selected item is represented by a new object instance with new `key`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/307)

Override combobox _isItemSelected to highlight remapped selected item

---

vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java

Explicitly remove old dataprovider listener when new one is set, not doing so can cause memory leakage
Fixes: https://github.com/vaadin/vaadin-combo-box-flow/issues/383

Explicitly remove old dataprovider listener when new one is set

---

vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java

Explicitly remove old dataprovider listener when new one is set (#382)
