vaadin/vaadin-combo-box-flow

- pom.xml
- src/test/java/com/vaadin/ui/combobox/ComboBoxIT.java
add dependency to POM;
add ComboBoxIT
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/7)
> Add ComboBox IT test class

- src/test/java/com/vaadin/ui/combobox/ComboBoxIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/8)
> remove the getTestPath method

- pom.xml
- src/main/java/com/vaadin/ui/combobox/ComboBox.java
- src/test/java/com/vaadin/ui/combobox/ComboBoxIT.java
- src/test/java/com/vaadin/ui/combobox/ComboBoxView.java
+ This is done because otherwise the parent-pom, flow-component, can't
be resolved;
+ modify the flow-data scope
+ using correct import for ItemLabelGenerator
- remove the main method in IT
+ add comment to the main mehod in view class
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/10)
> Add Flow repositories to pom.xml

- pom.xml
using flow-component-base alpha2 and release repo;
using flow alpha9;
update to 1.0-SNAPSHOT
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/12)
> Prepare for Release

- README.md
- pom.xml
- src/test/java/com/vaadin/ui/combobox/ComboBoxIT.java
- src/test/java/com/vaadin/ui/combobox/ComboBoxTest.java
- src/test/java/com/vaadin/ui/combobox/ComboBoxView.java
this is related to ticket vaadin/flow#2795
+component UI test;
+add Route title, as it can cause conflict to use default route;
+override getTestPath();
+Update parent and dependency version to SNAPSHOT;
+Update README
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/14)
> Prepare to build Demo jar of the component

- src/main/java/com/vaadin/ui/combobox/ComboBox.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/19)
> Remove unneeded HasItems, it is super interface of HasDataProvider.

- pom.xml
- src/test/java/com/vaadin/ui/combobox/ComboBoxPage.java
- src/test/java/com/vaadin/ui/combobox/ComboBoxPageIT.java
and add necessary dependency
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/21)
> Move more IT tests to its repo

- src/test/java/com/vaadin/ui/combobox/demo/ComboBoxView.java
- src/test/java/com/vaadin/ui/combobox/test/ComboBoxIT.java
- src/test/java/com/vaadin/ui/combobox/test/ComboBoxPage.java
- src/test/java/com/vaadin/ui/combobox/test/ComboBoxPageIT.java
- src/test/java/com/vaadin/ui/combobox/test/ComboBoxTest.java
change the route title for combo-box view #23  and fix the issue with #22
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/24)
> Refactor the repo structure

- src/main/java/com/vaadin/ui/combobox/ComboBox.java
- src/test/java/com/vaadin/ui/combobox/test/ComboBoxTest.java
Fix for #2996
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/26)
> Throw an exception if the generator return value is null

- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
- src/test/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java
- src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxIT.java
- src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxPage.java
- src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxPageIT.java
- src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxTest.java
Fix for #3032 in this repo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/29)
> Rename package name com.vaadin.ui to com.vaadin.flow.component

- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
- src/test/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java
- src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxPage.java
The part of package rename #3032
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/30)
> Correct imports after package rename in the server module

- README.md
- src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxIT.java
The running component demo link was faulty.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/33)
> Fixed read me link

- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- src/test/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java
- src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxIT.java
- src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxPage.java
- src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxPageIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/35)
> Add support for TemplateRenderers on ComboBox

- .gitignore
- src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
- src/test/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java
update gitignore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/40)
> Update generated file and add lumo style to demo

- src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java
Add a test inspired by a BeverageBuddy use case. This covers the usage of the component with Binder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/41)
> Add a unit test using binder

- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
- src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxPageIT.java
update the generated file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/42)
> Update comboBox Java side API

- pom.xml
- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
add slf4j-simple dependency
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/44)
> add addCustomValueSetListener as public java API

- pom.xml
- src/test/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java
rename repository id;
remove HtmlImport from component demo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/47)
> Using new webjars

- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- src/test/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java
- src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxIT.java
- src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxPage.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/51)
> Migrate to the new Renderer abstraction

- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java
Fixes #48
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/52)
> Update property value when selection is done instead of calling JS

- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/56)
> Use the new beforeClientResponse API

- src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java
Closes #36
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/58)
> Ensure ComboBox is focusable

- pom.xml
- src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/59)
> Update webjars to 4.0.0-beta4

- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
fix after vaadin/flow#3678
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/60)
> Update generated code

- pom.xml
- src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/63)
> Update webcomponent to 4.0.0-beta5

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/64)
> Update text-field version

- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java
- src/test/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java
- src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxIT.java
Add demo for disabled comboBox;
Add related unit and IT tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/65)
> Adjustment after flow hasEnabled interface

- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/66)
> Make ComboBox refresh items on enabled state changed.

- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/71)
> Update ComboBox to use the new AbstractField structure

- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/74)
> Fix ComboBox for the new HasValue interface

- pom.xml
- src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/75)
> Update vaadin-combo-box to 4.0.1

- pom.xml
- src/test/java/com/vaadin/flow/component/combobox/test/ComboboxSerializableTest.java
Related to vaadin/platform/issues/173
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/80)
> Add serialization test

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/82)
> Add section for installing component

- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java
- src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxPage.java
- src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxPageIT.java
Add test case;
Fixes#83.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/84)
> Keep the value before disabling the component

- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- src/test/java/com/vaadin/flow/component/combobox/test/PreSelectedValueIT.java
- src/test/java/com/vaadin/flow/component/combobox/test/PreSelectedValuePage.java
Fixes #85
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/86)
> Regenerate json object value on key mapper reset

- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- src/test/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java
- src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxPage.java
- src/test/java/com/vaadin/flow/component/combobox/test/StringItemsWithTextRendererIT.java
- src/test/java/com/vaadin/flow/component/combobox/test/StringItemsWithTextRendererPage.java
Fixes #77
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/87)
> Add component renderer import to the combobox class

- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- src/test/java/com/vaadin/flow/component/combobox/test/RefreshDataProviderIT.java
- src/test/java/com/vaadin/flow/component/combobox/test/RefreshDataProviderPage.java
Fixes #78
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/89)
> Listen for data change event in data provider

- README.md
- pom.xml
Update Readme
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/95)
> Update to 1.1 SNAPSHOT

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/94)
> Update Readme about branch scheme

- pom.xml
- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- src/test/java/com/vaadin/flow/component/combobox/test/ComponentRendererIT.java
- src/test/java/com/vaadin/flow/component/combobox/test/ComponentRendererPage.java
Fixes #97
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/99)
> Request re-rendering of the items.

- pom.xml
- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- src/test/java/com/vaadin/flow/component/combobox/test/ComponentRendererIT.java
- src/test/java/com/vaadin/flow/component/combobox/test/ComponentRendererPage.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/101)
> Request re-rendering of the items. (#99)

- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- src/test/java/com/vaadin/flow/component/combobox/test/ClearValueIT.java
- src/test/java/com/vaadin/flow/component/combobox/test/ClearValuePage.java
Closes https://github.com/vaadin/flow/issues/4359
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/102)
> Fix `clear()` method.

- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java
- src/test/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java
- src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxIT.java
Add demo and tests;
Remove the exception thrown by the component and related tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/103)
> Add nullRepresenation API to comboBox

- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- src/test/java/com/vaadin/flow/component/combobox/test/ClearValueIT.java
- src/test/java/com/vaadin/flow/component/combobox/test/ClearValuePage.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/104)
> Fix `clear()` method. (#102)

- pom.xml
- src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/96)
> Update webjar with material theme

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/106)
> Depend on all WebJars explicitly to avoid version ranges in resulting jars.

- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java
- src/test/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java
- src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxIT.java
This reverts commit a372c65435296f49714fd1f5b89421e7ba117dda.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/108)
> Revert "Add nullRepresenation API to comboBox (#103)"

- pom.xml
- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java
- src/test/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java
- src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxIT.java
- src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxPage.java
- src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxPageIT.java
close #46
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/109)
> Add null representation APIs

- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java
- src/test/java/com/vaadin/flow/component/combobox/bean/TestItem.java
- src/test/java/com/vaadin/flow/component/combobox/test/DataProviderIT.java
- src/test/java/com/vaadin/flow/component/combobox/test/DataProviderPage.java
Fixes #111
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/117)
> Using DataProvider::getId in setValue to find the item

- README.md
Part of fix for vaadin-button-flow#83
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/125)
> Update readme with the link to the docs and branching

- src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/127)
> Update java wrapper to stable version

- src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/145)
> Remove workaround (fixed in web component)

- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java
Fix #146
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/147)
> Improve exception message for setValue without DataProvider

- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- src/test/java/com/vaadin/flow/component/combobox/test/FilteringIT.java
- src/test/java/com/vaadin/flow/component/combobox/test/FilteringPage.java
to support a use-case where empty filter returns no items.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/151)
> Allow filtering based on empty string

- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java
Fix #148
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/150)
> Allow clearing ComboBox without data provider

- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
Resolve #149
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/152)
> Clarify filter-converting in setDataProvider javadocs

- pom.xml
- src/main/java/com/vaadin/flow/component/combobox/osgi/ComboBoxConnectorResource.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/163)
> Adding combo box connector resource registration for OSGi

- pom.xml
- src/main/java/com/vaadin/flow/component/combobox/osgi/ComboBoxConnectorResource.java
* Adding combo box connector resource registration for OSGi
(cherry picked from commit 5a707b8fb80eed7e42a02d87efc7b0c1f12c9904)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/164)
> Adding combo box connector resource registration for OSGi (#163)

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/165)
> removed obsolete jetty version

- src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
- src/test/java/com/vaadin/flow/component/combobox/test/AbstractComboBoxIT.java
- src/test/java/com/vaadin/flow/component/combobox/test/AutoFocusFilterIT.java
- src/test/java/com/vaadin/flow/component/combobox/test/AutoFocusFilterPage.java
- src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxPageIT.java
Data request using filter in combobox will provide also the filter in the response, so that any response for a different filter than the last one will be ignored.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/191)
> Set filter on autofocus combobox

- vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/RequiredComboboxPage.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/AbstractComboBoxIT.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/RequiredComboboxIT.java
- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
Fixes #179
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/202)
> Disable client side validation on setRequiredIndicatorVisible

- vaadin-combo-box-flow/pom.xml
- vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
Needs to be cherry-picked to 2.1 branch.
Release as 2.1.1?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/207)
> combo 4.2.5 + text 2.3.0

- vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/DataProviderPage.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/DataProviderIT.java
Test for a bug fixed in the web component:
https://github.com/vaadin/vaadin-combo-box/pull/771
Close #177, close #159
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/205)
> Add IT for decreasing the data set size

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/210)
> Bump flow version to 1.4-SNAPSHOT

- .gitignore
- pom.xml
- vaadin-combo-box-flow-integration-tests/build-tools/package.json
- vaadin-combo-box-flow-integration-tests/pom.xml
- vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/bean/SimpleBean.java
- vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/DataProviderPage.java
- vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/LazyLoadingPage.java
- vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/RefreshDataProviderPage.java
- vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/RequiredComboboxPage.java
- vaadin-combo-box-flow-integration-tests/src/main/webapp/frontend/bower.json
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/AbstractComboBoxIT.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/DataProviderIT.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/RefreshDataProviderIT.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/RequiredComboboxIT.java
- vaadin-combo-box-flow/pom.xml
- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
Rebase
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/213)
> 2.1.1 cherry picks

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/215)
> Update readme for demo

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/214)
> comp base 1.3.0-SNAPSHOT -> 1.3-SNAPSHOT

- pom.xml
- vaadin-combo-box-flow-demo/pom.xml
- vaadin-combo-box-flow-integration-tests/pom.xml
- vaadin-combo-box-flow-testbench/pom.xml
- vaadin-combo-box-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/221)
> Update to next minor and Use flow 1.5-SNAPSHOT

- vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/template/ValidationConnectorErrorPage.java
- vaadin-combo-box-flow-integration-tests/src/main/webapp/frontend/src/validation-connector.html
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/template/ValidationConnectorErrorIT.java
- vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/223)
> Check whether the combobox shadow root is not null

- vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/template/ValidationConnectorErrorPage.java
- vaadin-combo-box-flow-integration-tests/src/main/webapp/frontend/src/validation-connector.html
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/template/ValidationConnectorErrorIT.java
- vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
Fixes #219
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/225)
> Check whether the combobox shadow root is not null (#223)

- vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/LazyLoadingPage.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/AbstractComboBoxIT.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java
- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
Cherrypicking latest bug fixes for a maintenance release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/238)
> 2.1.3 cherrypicks

- vaadin-combo-box-flow-demo/src/main/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/AbstractComboBoxIT.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxIT.java
- vaadin-combo-box-flow/pom.xml
- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
- vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java
Breaking change: With the latest web component version, the clear button is hidden by default.
Fix #228 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/247)
> Add clear button visible API (breaking change)

- vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/RequiredComboboxPage.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/RequiredComboboxIT.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/SetItemsLaterIT.java
- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
fix #235
fix https://github.com/vaadin/flow/issues/5082
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/252)
> Init $connector in constructor

- vaadin-combo-box-flow/pom.xml
- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/257)
> Bump to latest web component version

- vaadin-combo-box-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/258)
> lock text-field version.

- vaadin-combo-box-flow-demo/src/main/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java
fix #256
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/259)
> Add demo for custom-value feature

- vaadin-combo-box-flow-demo/pom.xml
- vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
Fixes vaadin/flow#5702
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/261)
> Update bower dependencies to npm

- vaadin-combo-box-flow-demo/pom.xml
- vaadin-combo-box-flow-integration-tests/pom-bower-mode.xml
- vaadin-combo-box-flow-integration-tests/pom.xml
- vaadin-combo-box-flow-testbench/pom.xml
- vaadin-combo-box-flow-testbench/src/main/java/com/vaadin/flow/component/combobox/testbench/ComboBoxElement.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/262)
> Remove components testbench

- vaadin-combo-box-flow/pom.xml
- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/265)
> Update WC version

- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/264)
> Fix connector path in @JsModule

- vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/DetachReattachPage.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/DetachReattachIT.java
- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
fix #267
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/268)
> Init $connector on attach

- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
fix #185
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/274)
> Improve JavaDocs on page size

- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
fix #200
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/273)
> Add to docs that changing data provider resets value

- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java
- vaadin-combo-box-flow/pom.xml
- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/275)
> Bump web component dependency to 5.0.3

- vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/ClearValuePage.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ClearValueIT.java
- vaadin-combo-box-flow/pom.xml
- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
Connected to https://github.com/vaadin/vaadin-combo-box-flow/issues/277
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/281)
> Bump wc dependency and add test for clear button

- vaadin-combo-box-flow/pom.xml
- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/282)
> Bump wc deps

- vaadin-combo-box-flow-demo/src/main/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java
- vaadin-combo-box-flow-demo/src/main/java/com/vaadin/flow/component/combobox/demo/data/DepartmentData.java
- vaadin-combo-box-flow-demo/src/main/java/com/vaadin/flow/component/combobox/demo/data/ElementsData.java
- vaadin-combo-box-flow-demo/src/main/java/com/vaadin/flow/component/combobox/demo/data/PersonData.java
- vaadin-combo-box-flow-demo/src/main/java/com/vaadin/flow/component/combobox/demo/entity/Department.java
- vaadin-combo-box-flow-demo/src/main/java/com/vaadin/flow/component/combobox/demo/entity/Elements.java
- vaadin-combo-box-flow-demo/src/main/java/com/vaadin/flow/component/combobox/demo/entity/Person.java
- vaadin-combo-box-flow-demo/src/main/java/com/vaadin/flow/component/combobox/demo/entity/Song.java
- vaadin-combo-box-flow-demo/src/main/java/com/vaadin/flow/component/combobox/demo/service/PersonService.java
- vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/ComboBoxDemoPage.java
- vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/ComponentRendererPage.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/286)
> ComboBox demo improvement

- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/AbstractComboBoxIT.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/CustomValueIT.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/DataProviderIT.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/RefreshDataProviderIT.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/SetItemsLaterIT.java
- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
Fixes #288
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/291)
> Fix data request range

- vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/SetItemsLaterPage.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/SetItemsLaterIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/297)
> Select by tagname -> id in tests

- vaadin-combo-box-flow/pom.xml
- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/298)
> Bump web component version

- vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/FilterDebouncePage.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/FilterDebounceIT.java
- vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
Fixes #296 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/302)
> Fix for filtering problem using slow DataProvider - 296

- vaadin-combo-box-flow/pom.xml
- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/311)
> Bump versions, update WC dependency to 5.0.9

- vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
Connected to https://github.com/vaadin/components-team-tasks/issues/479
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/283)
> Improve error handling in connector: wrap with try catch

- vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
Make the `Flow.tryCatchWrapper` called lazily.
> Fix connector tryCatchWrapper definition

- vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
Align with https://github.com/vaadin/vaadin-grid-flow/pull/847
Connected to vaadin/vaadin-combo-box-flow#313
> Fix wrapped initLazy definition

- .gitignore
- vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/ChangeValueAndVisibilityPage.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ChangeValueAndVisibilityIT.java
- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
Remove unneeded workaround
Add regression tests the issue
Fixes #321
> Avoid extra value change to null when changing visibility

- vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/ChangeValueAndVisibilityPage.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ChangeValueAndVisibilityIT.java
- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
Remove unneeded workaround
Add regression tests the issue
> Avoid extra value change to null when changing visibility (#334)

- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
Fixes https://github.com/vaadin/90min-dx-tasks/issues/107
> Add Javadoc for setRenderer method

- pom.xml
- vaadin-combo-box-flow-demo/src/main/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java
- vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/LazyLoadingPage.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java
- vaadin-combo-box-flow-testbench/src/main/java/com/vaadin/flow/component/combobox/testbench/ComboBoxElement.java
- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java
Also update to latest flow-component-base
> Rename autoOpenDisabled to autoOpen

- vaadin-combo-box-flow-demo/src/main/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java
Fixes https://github.com/vaadin/vaadin-combo-box-flow/issues/353
> Shortening the titles of presentation demo

- vaadin-combo-box-flow-demo/src/main/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java
For users to be able to use code correctly by copy-pasting
Depends on https://github.com/vaadin/flow/pull/8199/files
Also fixes https://github.com/vaadin/vaadin-combo-box-flow/issues/353
> Add add-method call to make code complete

- vaadin-combo-box-flow-demo/pom.xml
- vaadin-combo-box-flow/pom.xml
- Bump webjar alphas to stable
- Bump snapshot dependency
> Bump dependencies

- vaadin-combo-box-flow-demo/src/main/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java
- vaadin-combo-box-flow-demo/src/main/java/com/vaadin/flow/component/combobox/demo/service/PersonService.java
- vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/LazyLoadingPage.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java
- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
Part of https://github.com/vaadin/flow/issues/8557
Make a Combobox init the data communicator with the page size
> Support for paged repositories

- vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/LazyLoadingPage.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java
- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
> Change DC page size when changing the page size for component

- vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/ComboBoxPage.java
- vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/LazyLoadingPage.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxIT.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxPageIT.java
- vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java
- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
> Avoid calling DataProvider::size before data is requested #242

- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
> Explicitly remove old dataprovider listener when new one is set (#382)

- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
- vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
- vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java
> Don't set value if Element has property "value"
